pub mod app;
#[cfg(feature = "arp")]
pub mod arp;
pub mod chrome_bridge;
pub mod config;
pub mod db;
pub mod debug_capturer;
pub mod downloads;
pub mod extensions;
pub mod frame_tasks;
pub mod gfx;
pub mod git;
pub mod i18n;
pub mod input;
#[cfg(feature = "lua")]
pub mod lua;
#[cfg(feature = "mcp")]
pub mod mcp;
pub mod net;
pub mod offscreen_webview;
#[cfg(feature = "passwords")]
pub mod passwords;
pub mod platform;
pub mod popup;
pub mod profiling;
pub mod scripts;
pub mod servo;
#[cfg(feature = "sync")]
pub mod sync;
#[cfg(feature = "terminal")]
pub mod terminal;
pub mod test_harness;
pub mod ui;
pub mod update_check;
pub mod wm;
pub mod workspace_restore;
pub mod wry_actions;
